# /etc/openfortivpn/config
protocol = ipsec
host = vpn.server.com
saml-login = 1
#username = <user>
#password = <password>
ipsec-psk = xxx
ipsec-auth = eap-mschapv2
ipsec-ike-proposals = aes256-sha256-ecp384
ipsec-esp-proposals = aes256-sha256-ecp384
ipsec-dpd-delay = 60
